// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDiCDeE73he23bZzWgYZ6Rvds1N6BoSVM',
    appId: '1:286172253797:web:b8abbf947de95f039ac08c',
    messagingSenderId: '286172253797',
    projectId: 'cadance-9cd1d',
    authDomain: 'cadance-9cd1d.firebaseapp.com',
    storageBucket: 'cadance-9cd1d.firebasestorage.app',
    measurementId: 'G-29M1MYTRTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKmRBwZlDpbN5H6XbGpGbyzxdOjxR6dF4',
    appId: '1:286172253797:android:7dfe481aef413d669ac08c',
    messagingSenderId: '286172253797',
    projectId: 'cadance-9cd1d',
    storageBucket: 'cadance-9cd1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ugiGX0eMbvyuvnVGWz2d_q3F6wpFpmU',
    appId: '1:286172253797:ios:6c2e0e6626a61bea9ac08c',
    messagingSenderId: '286172253797',
    projectId: 'cadance-9cd1d',
    storageBucket: 'cadance-9cd1d.firebasestorage.app',
    iosBundleId: 'com.example.pomodoro',
  );
}
